{
 "title": "Loki log statistics",
 "tags": [
  "loki",
  "log"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log size growth in time range",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(loki_recording:bytes:sum1m[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log size written",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "loki_recording:bytes:sum1m",
     "legendFormat": "{{host_name}} | {{host_ip}} | {{container_name}} | {{container_id}}"
    }
   ]
  },
  {
   "title": "Log size growth in time range",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum_over_time(loki_recording:bytes:sum1m[$__range])",
     "legendFormat": "{{host_name}} | {{host_ip}} | {{container_name}} | {{container_id}}"
    }
   ]
  },
  {
   "title": "Log size write rate in past 1m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(loki_recording:bytes_per_second:rate1m)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log size write rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "loki_recording:bytes_per_second:rate1m",
     "legendFormat": "{{host_name}} | {{host_ip}} | {{container_name}} | {{container_id}}"
    }
   ]
  },
  {
   "title": "Log size write rate in past 1m",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "loki_recording:bytes_per_second:rate1m",
     "legendFormat": "{{host_name}} | {{host_ip}} | {{container_name}} | {{container_id}}"
    }
   ]
  },
  { "title": "Number", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Log growth in time range",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(loki_recording:logs:count1m[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log written",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 22 },
   "targets": [
    {
     "expr": "loki_recording:logs:count1m",
     "legendFormat": "{{host_name}} | {{host_ip}} | {{container_name}} | {{container_id}}"
    }
   ]
  },
  {
   "title": "Log growth in time range",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum_over_time(loki_recording:logs:count1m[$__range])",
     "legendFormat": "{{host_name}} | {{host_ip}} | {{container_name}} | {{container_id}}"
    }
   ]
  },
  {
   "title": "Log growth rate in past 1m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "/sec" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(loki_recording:logs_per_second:rate1m)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log write rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "/sec" } },
   "targets": [
    {
     "expr": "loki_recording:logs_per_second:rate1m",
     "legendFormat": "{{host_name}} | {{host_ip}} | {{container_name}} | {{container_id}}"
    }
   ]
  },
  {
   "title": "Log growth rate in past 1m",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "/sec" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "loki_recording:logs_per_second:rate1m",
     "legendFormat": "{{host_name}} | {{host_ip}} | {{container_name}} | {{container_id}}"
    }
   ]
  }
 ]
}