services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle # https://prometheus.io/docs/prometheus/latest/migration/#prometheus-lifecycle
      - --web.enable-remote-write-receiver
    volumes:
      - ./resources/prometheus:/etc/prometheus
      - ./data/prometheus:/prometheus/data # https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects
    ports:
      - 9090:9090
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    command:
      - --config=/etc/grafana/grafana.ini
    volumes:
      - ./resources/grafana:/etc/grafana
      - ./data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true # for test
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin # for test
    restart: unless-stopped

  pushgateway:
    container_name: pushgateway
    image: prom/pushgateway
    command:
      - --persistence.file=/data/metric.store
      - --persistence.interval=5m
    volumes:
      - ./data/pushgateway:/data
    ports:
      - 9091:9091
    restart: unless-stopped

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/data
      - --data.maintenance-interval=5m
    volumes:
      - ./resources/alertmanager:/etc/alertmanager
      - ./data/alertmanager:/data
    ports:
      - 9093:9093
    restart: unless-stopped

  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter
    command:
      - --path.rootfs=/host
    network_mode: host
    pid: host
    volumes:
      - /:/host:ro,rslave
    restart: unless-stopped

  blackbox_exporter:
    container_name: blackbox_exporter
    image: prom/blackbox-exporter
    command:
      - --config.file=/etc/blackbox_exporter/blackbox.yml
    volumes:
      - ./resources/blackbox_exporter:/etc/blackbox_exporter
    ports:
      - 9115:9115
    restart: unless-stopped

  # https://raw.githubusercontent.com/grafana/loki/main/production/docker-compose.yaml
  loki:
    container_name: loki
    image: grafana/loki
    command:
      - -config.file=/etc/loki/config.yaml
    volumes:
      - ./resources/loki:/etc/loki
      - ./data/loki:/loki
    ports:
      - 3100:3100
    restart: unless-stopped

  promtail:
    container_name: promtail
    image: grafana/promtail
    command:
      - -config.file=/etc/promtail/config.yaml
      - -config.expand-env=true # https://grafana.com/docs/loki/latest/send-data/promtail/configuration/#use-environment-variables-in-the-configuration
    volumes:
      - ./resources/promtail:/etc/promtail
      - ./data/promtail:/tmp
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
      - HOST_NAME=${HOST_NAME}
      - HOST_IP=${HOST_IP}
    restart: unless-stopped

  # cadvisor:
  #   container_name: cadvisor
  #   image: gcr.io/cadvisor/cadvisor
  #   devices:
  #     - /dev/kmsg
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:ro
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #     - /dev/disk/:/dev/disk:ro
  #   ports:
  #     - 8080:8080
  #   restart: unless-stopped
