services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle # https://prometheus.io/docs/prometheus/latest/migration/#prometheus-lifecycle
    volumes:
      - ./resources/prometheus:/etc/prometheus
      - ./data/prometheus:/prometheus/data # https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects
    ports:
      - 9090:9090
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    command:
      - --config=/etc/grafana/grafana.ini
    volumes:
      - ./resources/grafana:/etc/grafana
      - ./data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true # for test
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin # for test
    restart: unless-stopped

  pushgateway:
    container_name: pushgateway
    image: prom/pushgateway
    command:
      - --persistence.file=/data/metric.store
      - --persistence.interval=1m
    volumes:
      - ./data/pushgateway:/data
    ports:
      - 9091:9091
    restart: unless-stopped

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    volumes:
      - ./resources/alertmanager:/etc/alertmanager
    ports:
      - 9093:9093
    restart: unless-stopped

  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter
    command:
      - --path.rootfs=/host
    network_mode: host
    pid: host
    volumes:
      - /:/host:ro,rslave
    restart: unless-stopped

  blackbox_exporter:
    container_name: blackbox_exporter
    image: prom/blackbox-exporter
    command:
      - --config.file=/etc/blackbox_exporter/blackbox.yml
    volumes:
      - ./resources/blackbox_exporter:/etc/blackbox_exporter
    ports:
      - 9115:9115
    restart: unless-stopped

  # https://raw.githubusercontent.com/grafana/loki/main/production/docker-compose.yaml
  loki:
    container_name: loki
    image: grafana/loki
    command:
      - -config.file=/etc/loki/config.yaml
    volumes:
      - ./resources/loki:/etc/loki
    ports:
      - 3100:3100

  promtail:
    container_name: promtail
    image: grafana/promtail
    command:
      - -config.file=/etc/promtail/config.yaml
    volumes:
      - ./resources/promtail:/etc/promtail
      - ./data/promtail:/tmp
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
