services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle" # https://prometheus.io/docs/prometheus/latest/migration/#prometheus-lifecycle
    volumes:
      - ./components/prometheus:/etc/prometheus
      - ./data/prometheus:/prometheus/data # https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects
    ports:
      - 9090:9090
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    command:
      - "--config=/etc/grafana/grafana.ini"
    volumes:
      - ./components/grafana:/etc/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
