services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
