global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/prometheus/rules/*.yml
  - /etc/prometheus/rules/*.yaml

scrape_configs:
  - # https://prometheus.io/docs/guides/file-sd/
    job_name: file_sd
    file_sd_configs:
      - refresh_interval: 5m
        files:
          - /etc/prometheus/targets.json

  # - job_name: cadvisor
  #   scrape_interval: 5s
  #   file_sd_configs:
  #     - files:
  #         - /etc/prometheus/cadvisor.json

  # https://min.io/docs/minio/linux/operations/monitoring/collect-minio-metrics-using-prometheus.html
  # 1. run `mc alias ls`
  # 2. edit `/tmp/.mc/config.json`, fill accessKey(username) and secretKey(password)
  # 3. run `mc admin prometheus generate local`
  - job_name: minio-job
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoibW9uaXRvcmluZyIsImV4cCI6NDg3OTUzOTg0MX0.44-v83Ssx8OA7UCoXKA9HBoghoKOmSehrg73BSfnrF9QdPuLxi2t8GyY45YDl5Go7K3i0WPQSwIVdiTmI96UrQ
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: ["minio:9000"]
