positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    external_labels:
      host_name: ${HOST_NAME}
      host_ip: ${HOST_IP}

scrape_configs:
  - # https://grafana.com/docs/loki/latest/send-data/promtail/configuration/#docker_sd_configs
    job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_log_stream]
        target_label: log_stream

      - source_labels: [__meta_docker_container_id]
        target_label: container_id

      - source_labels: [__meta_docker_container_name]
        regex: /(.*)
        target_label: container_name

      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        target_label: compose_project

      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: compose_service

      - source_labels: [__meta_docker_container_name]
        action: replace
        regex: /(.*)
        replacement: /var/lib/docker/containers/$1/*.log
        target_label: __path__
