# https://grafana.com/docs/loki/latest/configure/
---
auth_enabled: false # https://grafana.com/docs/loki/latest/operations/multi-tenancy/

common:
  # https://github.com/grafana/loki/issues/14116
  path_prefix: /loki
  # too many unhealthy instances in the ring
  # https://github.com/grafana/loki/issues/10537
  replication_factor: 1

memberlist:
  join_members:
    - loki:7946

schema_config:
  configs:
    # https://grafana.com/docs/loki/latest/configure/#period_config
    - from: 2024-08-01
      store: boltdb-shipper
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

# https://grafana.com/docs/loki/latest/configure/#storage_config
# https://blog.min.io/how-to-grafana-loki-minio/
# https://github.com/ruanbekker/loki-minio-docker/blob/main/config/loki.yaml
storage_config:
  aws:
    s3: s3://monitoring:monitoring@minio.:9000/loki
    s3forcepathstyle: true

# https://grafana.com/docs/loki/latest/configure/#ruler
# https://github.com/grafana/loki/issues/7589
ruler:
  wal:
    dir: /loki/ruler-wal
  alertmanager_url: http://alertmanager:9093
  enable_alertmanager_v2: true
  enable_api: true
  remote_write:
    enabled: true
    client:
      url: http://prometheus:9090/api/v1/write

analytics:
  reporting_enabled: false
