# https://grafana.com/docs/loki/latest/configure/
---
auth_enabled: false # https://grafana.com/docs/loki/latest/operations/multi-tenancy/

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-08-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

# https://grafana.com/docs/loki/latest/configure/#ruler
# https://github.com/grafana/loki/issues/7589
ruler:
  wal:
    dir: /loki/ruler-wal
  storage:
    type: local
    local:
      directory: /etc/loki/rules
  alertmanager_url: http://alertmanager:9093
  enable_alertmanager_v2: true
  enable_api: true
  remote_write:
    enabled: true
    client:
      url: http://prometheus:9090/api/v1/write

analytics:
  reporting_enabled: false
