# https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file
---
apiVersion: 1

datasources:
  - # https://grafana.com/docs/grafana/latest/datasources/prometheus/#provisioning-example
    name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: false

  - # https://grafana.com/docs/grafana/latest/datasources/loki/#provisioning-examples
    name: Loki
    type: loki
    url: http://loki:3100
    access: proxy
    isDefault: false
    editable: false
